### ISSUE TITLE
[Dashboards 7.x] Problems loading visualizations for Services, Errors and Transactions dashboards

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-contrib#11]
I haven't problems on some of the 7.x dashboards, where certain visualizations don't load.

#### Services

![screencapture-localhost-5601-doi-app-kibana-2019-02-28-13_00_19](https://user-images.githubusercontent.com/4104278/53565205-14497f80-3b59-11e9-9689-e5e2211372a8.png)

#### Errors

![screencapture-localhost-5601-doi-app-kibana-2019-02-28-13_00_27](https://user-images.githubusercontent.com/4104278/53565208-17447000-3b59-11e9-85c7-b16d1431ab82.png)

#### Transactions

![screencapture-localhost-5601-doi-app-kibana-2019-02-28-13_00_09](https://user-images.githubusercontent.com/4104278/53565214-1b708d80-3b59-11e9-8ec7-b3945281de1c.png)

cc @bmorelli25 @graphaelli

**Comment by graphaelli** [comment]
@formgeist do you have an apm-* index pattern?  The missing visualization in each case references the index pattern:

1, https://github.com/elastic/apm-contrib/blob/56ddaacb54a9ebc1f8410024a060f16c8d161ae2/apm-ui/7.x/services.json#L40
2. https://github.com/elastic/apm-contrib/blob/56ddaacb54a9ebc1f8410024a060f16c8d161ae2/apm-ui/7.x/errors.json#L35
3. https://github.com/elastic/apm-contrib/blob/56ddaacb54a9ebc1f8410024a060f16c8d161ae2/apm-ui/7.x/transactions.json#L40

I'm trying to reproduce locally still.

**Comment by graphaelli** [comment]
cancel that @formgeist, I'm able to reproduce when launching fresh on 7.0.  Upgrading from 6.6 doesn't trigger this, looking into it.

**Comment by formgeist** [comment]
@graphaelli Thanks for taking a look 👍

**Comment by graphaelli** [comment]
To reproduce, import this saved object and see "No objects imported":

```[
{
  "_id": "a2e199b0-7820-11e7-8c47-65b845b5cfb3",
  "_migrationVersion": {
    "visualization": "7.0.0"
  },
  "_references": [
    {
      "id": "apm-*",
      "name": "kibanaSavedObjectMeta.searchSourceJSON.index",
      "type": "index-pattern"
    }
  ],
  "_source": {
    "description": "",
    "kibanaSavedObjectMeta": {
      "searchSourceJSON": "{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"},\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"
    },
    "title": "Top Transactions for Time Period [APM]",
    "uiStateJSON": "{\"vis\": {\"params\": {\"sort\": {\"columnIndex\": null, \"direction\": null}}}}",
    "version": 1,
    "visState": "{\"type\":\"table\",\"params\":{\"sort\":{\"columnIndex\":null,\"direction\":null},\"perPage\":25,\"showPartialRows\":false,\"totalFunc\":\"sum\",\"showTotal\":false,\"showMeticsAtAllLevels\":false},\"aggs\":[{\"params\":{\"orderBy\":\"1\",\"field\":\"transaction.name.keyword\",\"customLabel\":\"Transaction\",\"order\":\"desc\",\"size\":1000},\"type\":\"terms\",\"enabled\":true,\"id\":\"2\",\"schema\":\"bucket\"},{\"params\":{\"sortField\":\"@timestamp\",\"customLabel\":\"Type\",\"field\":\"transaction.type\",\"sortOrder\":\"desc\",\"aggregate\":\"concat\",\"size\":1},\"type\":\"top_hits\",\"enabled\":true,\"id\":\"5\",\"schema\":\"metric\"},{\"params\":{\"field\":\"transaction.duration.us\",\"customLabel\":\"Avg. Resp Time (ms)\"},\"type\":\"avg\",\"enabled\":true,\"id\":\"1\",\"schema\":\"metric\"},{\"params\":{\"field\":\"transaction.duration.us\",\"customLabel\":\"Resp Time (ms)\",\"percents\":[95]},\"type\":\"percentiles\",\"enabled\":true,\"id\":\"3\",\"schema\":\"metric\"},{\"params\":{\"sortField\":\"@timestamp\",\"customLabel\":\"View Spans\",\"field\":\"transaction.id\",\"sortOrder\":\"desc\",\"aggregate\":\"concat\",\"size\":1},\"type\":\"top_hits\",\"enabled\":true,\"id\":\"4\",\"schema\":\"metric\"}],\"title\":\"Top Transactions for Time Period [APM]\"}"
  },
  "_type": "visualization"
}
]
```

**Comment by bmorelli25** [comment]
I'm still figuring these things out, so apologies if this is known or not important, but I was able to get the above 7.x dashboard to work by altering a `field` in the "visState" object. If you change `transaction.name.keyword` to any other field, like `transaction.name` for example, the viz loads.

Similarly, the other failing visualizations all have one bad field. For the [services](https://github.com/elastic/apm-contrib/blob/master/apm-ui/7.x/services.json) dashboard it's `"field\":\"view errors` on L59: https://github.com/elastic/apm-contrib/blob/56ddaacb54a9ebc1f8410024a060f16c8d161ae2/apm-ui/7.x/services.json#L59
 Change to `"field\":\"error.type` for example, it loads in.

**Comment by graphaelli** [comment]
good find @bmorelli25 ! `transaction.name.keyword` was moved in 7.0 and I missed updating that in the dashboard.  I also only just learned that `view errors` was removed from the default index pattern so it doesn't exist at all.
