### ISSUE TITLE
get warning when import error.json in 7.x folder(stack version 7.1.0)

### ISSUE THREAD

**Issue by Ellison001** [elastic/apm-contrib#22]
Hi, when I import the dashboard error.json and transaction.json from apm-contrib/apm-ui/7.x/ folder. The APM pops up with below error.

Saved "field" parameter is now invalid. Please select a new field.

stack version:
ES: 7.1.0
Kibana: 7.1.0
APM: 7.1.0

**Comment by axw** [comment]
I was not able to reproduce the issue.

- Is this a clean install?
- Did you perform the "Load Kibana objects" step in the APM app first? https://www.elastic.co/guide/en/kibana/current/apm-getting-started.html

**Comment by Ellison001** [comment]
@axw , It is not a fresh install. I upgrade the stack from 6.x.x to 7.1.0. will try the fresh install to see if I met the same issue.

**Comment by Ellison001** [comment]
fresh install don't have such issue. Thanks axw.

**Comment by axw** [comment]
Thanks for following up @Ellison001.
