### ISSUE TITLE
APM7.2.0 dashboard and virtualization

### ISSUE THREAD

**Issue by Ellison001** [elastic/apm-contrib#24]
Hi since APM7.2.0 is released. Do we have dashboard and virtualization created for the JVM metrics?

**Comment by axw** [comment]
You can find Kibana dashboards for JVM metrics here: https://github.com/elastic/apm-contrib/tree/master/apm-agent-java/dashboards. The APM UI also has support for a subset of JVM metrics in 7.2.0.
