### ISSUE TITLE
PHP Agent Supports v2 API

### ISSUE THREAD

**Issue by alash3al** [elastic/apm-contrib#28]
Dears,

There is a [PHP agent](https://github.com/philkra/elastic-apm-php-agent) that only supports `v1` API for the APM server,

I asked the maintainer about his plan regarding v2 support, but I think that he may be busy for now, and currently, so we decided to fork it, and just do some updates that make it support `v2` API, 

here is the package [https://github.com/speakol-ads/elastic-apm-php-agent](https://github.com/speakol-ads/elastic-apm-php-agent) also, we forked the `laravel` agent that depends on it and updated it, you can find it here [https://github.com/speakol-ads/elastic-apm-laravel](https://github.com/speakol-ads/elastic-apm-laravel)

We just wanted to help the php community, if you have any recommendation before adding the mentioned packages in your list, just ping me, and also what are the steps required to list them here?

**Comment by axw** [comment]
Thank you @alash3al, I'm no PHP developer but it looks great! I'm happy for it to be added to the list. The only step is to send a PR :)

I'll create a PR, since I'd like to also make a note of the versions supported by each agent.
