### ISSUE TITLE
Add Meteor apm agent

### ISSUE THREAD

**Issue by kschingiz** [elastic/apm-contrib#8]
Hi, I have developed meteor elastic agent. Will be happy to see it in this list:
 https://github.com/kschingiz/meteor-elastic-apm/

Thanks!

**Comment by watson** [comment]
Do you mean a link to your repo from the README?

**Comment by kschingiz** [comment]
@watson yes

**Comment by watson** [comment]
I've created a PR: #13 
Let me know what you think 😃

**Comment by kschingiz** [comment]
@watson that's great! Thanks!
